version: "3.8"

x-default: &default_sonarqube
  # restart: always
  env_file:
    - ./env_file.sonarqube
  logging:
    driver: "json-file"
    options:
      max-size: "10M"
      max-file: "3"
  networks:
    - sonarqube-network

services:
  sonarqube:
    <<: *default_sonarqube
    image: sonarqube:9.0.0-community
    container_name: sonarqube
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./tmp/data:/opt/sonarqube/data
      - ./tmp/logs:/opt/sonarqube/logs
      - ./plugins:/opt/sonarqube/extensions/plugins
    depends_on:
      - postgres-sonarqube
    # entrypoint: bash -c # sh -c
    # command:
    #   - while true; do echo "this is test command"; sleep 1; done


  postgres-sonarqube:
    <<: *default_sonarqube
    container_name: sonarqube-postgres
    hostname: ${SONARQUBE_POSTGRES_HOSTNAME:? this variable must be set}  # variable-substitution: https://docs.docker.com/compose/compose-file/compose-file-v3/#variable-substitution
    image: postgres:latest
    ports:
      - 5433:5432
    volumes:
      # - sonarqube_postgres:/var/lib/postgresql/data
      - ./tmp/postgres:/var/lib/postgresql/data

networks:
  sonarqube-network:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_postgres:
