version: '3'

services:
  my-backend:
    image: my-backend:1.1.1
    build: .
    env_file: env_file
    volumes:
      - .:/app
    networks:
      - internal-network
    ports:
      - 8027:8027
    depends_on:
      - postgres

  postgres:
    env_file: env_file
    image: postgres:10
    ports:
      - 5432:5432
    networks:
      - internal-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  internal-network:
    driver: bridge

volumes:
  postgres_data:
