version: '3'

services:
  my-backend:
    build: 
      args:
        BUILD_ENV: prod
    environment:
      - DEBUG=False
    restart: always

  postgres:
    restart: always

  nginx:
    restart: always
