version: '3.8'

services:
  my-backend:
    image: my-backend:int-latest
    build: 
      args:
        BUILD_ENV: int
    environment:
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=main.settings.int
      - WORKING_ENV=int
    restart: always
    # entrypoint: bash -c # sh -c
    command:
      - /bin/bash
      - -c
      - |
        python3 manage.py migrate
        gunicorn main.wsgi:application -w 5 -b :8027
    volumes:
      - static_files:/app/static_files

  postgres:
    restart: always

  nginx:
    restart: always
    volumes:
      - static_files:/home/www-data/static_files:ro

  celery-worker:
    build: 
      args:
        BUILD_ENV: int

  celery-beat:
    build: 
      args:
        BUILD_ENV: int
        
  # celery-flower:
  #   build: 
  #     args:
  #       BUILD_ENV: int


volumes:
  static_files:
