version: '3.8'

services:
  my-backend:
    build: 
      args:
        BUILD_ENV: prod
    environment:
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE:main.settings.prod
    restart: always

  postgres:
    restart: always

  nginx:
    restart: always
