version: '3.8'

x-default: &default
  restart: always
  env_file:
    - env_file
  logging:
    driver: "json-file"
    options:
      max-size: "100M"
      max-file: "3"
  networks:
    - internal-network

services:
  my-backend:
    <<: *default
    image: my-backend:1.1.1
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: my-sample-backend
    volumes:
      - .:/app
    ports:
      - 8027:8027
    depends_on:
      - postgres
    ## NOTE: below code for test container running
    # entrypoint: bash -c # sh -c
    # command:
    #   - while true; do echo "this is test command"; sleep 1; done


  postgres:
    <<: *default
    image: postgres:10
    container_name: my-sample-postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data


  nginx:
    <<: *default
    image: nginx:1.11.6
    container_name: my-sample-nginx
    depends_on:
        - my-backend
    ports:
        - 81:80
        - 444:443
    volumes:
        - ./nginx:/etc/nginx/conf.d:ro
    command: /bin/bash -c "nginx -g 'daemon off;'"

  
networks:
  internal-network:
    driver: bridge

volumes:
  postgres_data:
