version: '3.8'

services:
  my-backend:
    image: my-backend:prod-latest
    build: 
      args:
        BUILD_ENV: prod
    environment:
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=main.settings.prod
      - WORKING_ENV=prod
    restart: always
    # entrypoint: bash -c # sh -c
    command:
      - /bin/bash
      - -c
      - |
        python3 manage.py migrate
        gunicorn main.wsgi:application -w 1 -b :8027
    volumes:
      - static_files:/app/static_files
      - ./source:/app

  postgres:
    restart: always

  nginx:
    restart: always
    volumes:
      - static_files:/home/www-data/static_files:ro

  celery-worker:
    build: 
      args:
        BUILD_ENV: prod

  celery-beat:
    build: 
      args:
        BUILD_ENV: prod
        
  # celery-flower:
  #   build: 
  #     args:
  #       BUILD_ENV: prod


volumes:
  static_files:
