version: '3.8'

services:
  my-backend:
    image: my-backend:dev-latest
    build: 
      args:
        BUILD_ENV: dev
    environment:
        - DJANGO_SETTINGS_MODULE=main.settings.dev
        - WORKING_ENV=dev
    volumes:
      - ./source:/app
      - ./source/static_files:/app/static_files
    ports:
      - 5678:5678
    command:
      - /bin/bash
      - -c
      - |
        python3 manage.py migrate
        python3 manage.py collectstatic --noinput
        python3 manage.py runserver 0.0.0.0:8027
 
  nginx:
    volumes:
      - ./source/static_files:/home/www-data/static_files

  celery-worker:
    build: 
      args:
        BUILD_ENV: dev

  celery-beat:
    build: 
      args:
        BUILD_ENV: dev
        
  # celery-flower:
  #   build: 
  #     args:
  #       BUILD_ENV: dev
