version: '3.8'

x-default: &default
  env_file:
    - env_file
  logging:
    driver: "json-file"
    options:
      max-size: "100M"
      max-file: "3"
  networks:
    - internal-network


services:
  my-backend:
    <<: *default
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        IS_BUILDING_APP: "yes"
    volumes:
      - ./source/logs:/app/logs
    container_name: my-sample-backend
    ports:
      - 8027:8027
    depends_on:
      - postgres
    logging:
        driver: "json-file"
        options:
            max-size: "100M"
            max-file: "3"

  celery-worker:
    <<: *default
    image: celery-worker:latest
    build: 
      context: .
      dockerfile: Dockerfile
    command:
      - celery 
      - --app=main.celery_app 
      - worker 
      - -Q=queue-high,queue-medium,queue-low 
      - -Ofair
      - --pool=solo # TODO: nghien cuu xem tai sao pool la solo lai chay duoc con eventlet lai khong chay duoc task ben trong app coordinate
      - --concurrency=10 
      - --loglevel=info 
      - -f /app/logs/celery-worker.log 
      - -n worker1@%h
    volumes:
      - ./source:/app
      - ./source/logs:/app/logs
    container_name: my-sample-celery-worker

  celery-beat:
    <<: *default
    image: celery-beat:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./source:/app
      - ./source/logs:/app/logs
    container_name: my-sample-celery-beat
    command:
      celery --app=main.celery_app beat --loglevel=info -f /app/logs/celery-beat.log 

  # celery-flower:
  #   <<: *default
  #   image: celery-flower:latest
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./source:/app
  #     - ./source/logs:/app/logs
  #   container_name: my-sample-celery-flower
  #   ports:
  #     - 5555:5555
  #   depends_on:
  #     - postgres
  #   command:
  #     celery --app=main.celery_app flower --basic_auth=admin:password123 --address=0.0.0.0 --port=5555

  redis:
    <<: *default
    image: bitnami/redis:5.0
    container_name: my-sample-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    # - REDIS_PASSWORD=5Zu7fA8r5eaO
    ports:
      - 6379:6379
    volumes:
      - redis_data/:/data/
    hostname: redis

  postgres:
    <<: *default
    image: postgres:10
    container_name: my-sample-postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging:
        driver: "json-file"
        options:
            max-size: "100M"
            max-file: "3"


  frontend:
    <<: *default
    image: web:1.1.1
    build:
      context: ./react-googlemaps
      dockerfile: Dockerfile
    container_name: my-sample-frontend
    ports:
        - 3000:3000
    volumes:
        - ./react-googlemaps:/app


  nginx:
    <<: *default
    image: nginx:1.13
    container_name: my-sample-nginx
    depends_on:
        - my-backend
    ports:
        - 81:80
        - 444:443
    volumes:
        - ./nginx:/etc/nginx/conf.d:ro
    command: /bin/bash -c "nginx -g 'daemon off;'"

  
networks:
  internal-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
