version: '3.8'

x-default: &default
  env_file:
    - env_file
  logging:
    driver: "json-file"
    options:
      max-size: "100M"
      max-file: "3"
  networks:
    - internal-network

services:
  my-backend:
    <<: *default
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./source/logs:/app/logs
    container_name: my-sample-backend
    ports:
      - 8027:8027
    depends_on:
      - postgres

  postgres:
    <<: *default
    image: postgres:10
    container_name: my-sample-postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data


  nginx:
    <<: *default
    image: nginx:1.13
    container_name: my-sample-nginx
    depends_on:
        - my-backend
    ports:
        - 81:80
        - 444:443
    volumes:
        - ./nginx:/etc/nginx/conf.d:ro
    command: /bin/bash -c "nginx -g 'daemon off;'"

  
networks:
  internal-network:
    driver: bridge

volumes:
  postgres_data:
