# References example here: https://github.com/SonarSource/sonar-scanning-examples
# https://github.com/apache/thrift/blob/master/sonar-project.properties

# must be unique in a given SonarQube instance
sonar.projectKey=django_project
sonar.projectName=django_project

sonar.host.url=http://localhost:9000
# project's token
sonar.login=sqp_afb3c3c3cf04409e1d3a7b7d4507e4a5c5bed7ce

sonar.sourceEncoding=UTF-8

sonar.language=py

# sonar.projectBaseDir=/home/ftpdrop/cobol/project1
# Path is relative to the sonar-project.properties file. Defaults to .
sonar.sources=source

sonar.inclusions=**/**.py
# sonar.inclusions=source/music/management/commands/sample_create_celery_periodic_task.py

# sonar.exclusions=**/.*/**, **/test/**, **/logs/**, sonarqube/**
sonar.exclusions=sonarqube/**/*     # NOTE: this config does not work

# sonar.python.coverage.reportPaths=coverage.xml

sonar.search.javaAdditionalOpts=-Dcluster.routing.allocation.disk.threshold_enabled=false

