# Generated by Django 3.1 on 2021-05-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinate',
            name='battery_level',
            field=models.IntegerField(default=100),
        ),
    ]
