# Generated by Django 3.1 on 2021-05-07 06:40

from django.db import migrations


def create_sample_data(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    # Reference: https://stackoverflow.com/a/39742847/7639845
    UnlockScreenUrl = apps.get_model("screen", "UnlockScreenUrl")
    UnlockScreenUrl.objects.get_or_create(id=1, url="abc.com")


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_sample_data),
    ]
